version: 2.1
orbs:
  k8s: circleci/kubernetes@0.7.0
  slack: circleci/slack@3.4.2
commands:
  npm_install:
    description: "npm install and save cache"
    steps:
      - restore_cache:
          keys:
            - node-{{ checksum "package-lock.json" }}
            - node-
      - run:
          name: Install npm packages
          command: npm install
      - save_cache:
          key: node-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
  test:
    description: "Run npm test"
    steps:
      - run:
          name: "Run test"
          command: npm test
  build:
    description: "Build for release target"
    parameters:
      target:
        type: string
        default: "staging"
    steps:
      - run:
          name: Building dist for << parameters.target >>
          command: node_modules/grunt/bin/grunt releaseci --<< parameters.target >>
  versioning:
    description: "Add version to build"
    parameters:
      target_branch:
        type: string
    steps:
      - run:
          name: Tag build
          command: echo "<< parameters.target_branch >> $(date -u +'%Y-%m-%dT%H:%M:%SZ')" > dist/version
  docker_build_push:
    description: "Build Docker image"
    parameters:
      docker_latest_image_tag:
        type: string
        default: "latest-staging"
      docker_image_tag:
        type: string
        default: ${CIRCLE_SHA1}
    steps:
      - setup_remote_docker
      - run: 
          name: Building docker image
          command: |
            docker build -t ${DOCKHUB_ORGANISATION}/binary-static:<< parameters.docker_image_tag >> -t ${DOCKHUB_ORGANISATION}/binary-static:<< parameters.docker_latest_image_tag >> .
      - run: 
          name: Pushing Image to docker hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push ${DOCKHUB_ORGANISATION}/binary-static:<< parameters.docker_image_tag >>
            docker push ${DOCKHUB_ORGANISATION}/binary-static:<< parameters.docker_latest_image_tag >>
  k8s_deploy:
    description: "Deploy to k8s cluster"
    parameters:
      k8s_svc_name:
        type: string
        default: "staging-binary-com"
      k8s_namespace:
        type: string
        default: "www-binary-com-staging"
      k8s_version:
        type: string
        default: ${CIRCLE_SHA1}
    steps:
      - k8s/install-kubectl
      - run: 
          name: Deploying to k8s cluster for service << parameters.k8s_svc_name >>
          command: |
            TAG=${CIRCLE_TAG:-$CIRCLE_SHA1}
            export NAMESPACE=<< parameters.k8s_namespace >>
            git clone https://github.com/binary-com/devops-ci-scripts
            cd devops-ci-scripts/k8s-build_tools
            echo $CA_CRT | base64 --decode > ca.crt
            ./release.sh binary-static << parameters.k8s_version >>
  notify_slack:
    description: "Notify slack"
    steps:
      - slack/status:
          include_project_field: false
          failure_message: "Release failed for Binary.com with version *$(cat dist/version)*"
          success_message: "Release succeeded for Binary.com with version *$(cat dist/version)*"
          webhook: ${SLACK_WEBHOOK}
  publish_to_pages_staging:
    description: "Publish to cloudflare pages"
    steps:
      - run:
          name: "Publish to cloudflare pages (staging)"
          command: |
            cd dist
            npx wrangler pages publish . --project-name=binary-static-pages --branch=staging
            echo "New staging website - http://staging.cf-pages-binary-static.binary.com"

  publish_to_pages_production:
    description: "Publish to cloudflare pages"
    steps:
      - run:
          name: "Publish to cloudflare pages (production)"
          command: |
            cd dist
            npx wrangler pages publish . --project-name=binary-static-pages --branch=main
            echo "New website - http://cf-pages-binary-static.binary.com"
jobs:
  test:
    docker:
      - image: circleci/node:14-stretch
    steps:
      - checkout
      - npm_install
      - test
  release_staging:
    docker:
      - image: circleci/node:14-stretch
    steps:
      - checkout
      - npm_install
      - test
      - build:
         target: 'staging'
      - build:
          target: 'translations'
      - versioning:
          target_branch: "staging"
      - persist_to_workspace:
          root: dist
          paths:
            - .
      - versioning:
          target_branch: "staging"
      - docker_build_push
      - k8s_deploy
      - notify_slack
  release_production:
    docker:
      - image: circleci/node:14-stretch
    steps:
      - checkout
      - npm_install
      - test
      - build:
          target: 'production'
      - versioning:
          target_branch: "production"
      - persist_to_workspace:
          root: dist
          paths:
            - .
      - docker_build_push:
          docker_latest_image_tag: latest
          docker_image_tag: ${CIRCLE_TAG}
      - k8s_deploy:
          k8s_svc_name: "production-binary-com"
          k8s_namespace: "www-binary-com-production"
          k8s_version: ${CIRCLE_TAG}
      - notify_slack
  publish_cloudflare_staging:
    docker:
      - image: circleci/node:16.13.1-stretch
    steps:
      - attach_workspace:
          at: dist
      - publish_to_pages_staging
  publish_cloudflare_production:
    docker:
      - image: circleci/node:16.13.1-stretch
    steps:
      - attach_workspace:
          at: dist
      - publish_to_pages_production

workflows:
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: /^master$/
  release:
    jobs:
      - release_staging:
          filters:
            branches:
              only: /^master$/
          context: binary-frontend-artifact-upload
      - publish_cloudflare_staging:
          requires:
            - release_staging
          filters:
            branches:
              only: /^master$/
          context: binary-frontend-artifact-upload
      - release_production:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^production.*/
          context: binary-frontend-artifact-upload
      - publish_cloudflare_production:
          requires:
            - release_production
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^production.*/
          context: binary-frontend-artifact-upload
